/*
 * Responsive fixes for the Dashboard — Members handoff.
 *
 * The bundled build has zero @media queries, and its internal stylesheet handling
 * doesn't reliably support them either (an earlier attempt at a linked stylesheet
 * with @media blocks got its rules silently hoisted out of the media query and
 * applied unconditionally). This runs as plain JS instead: it sets real inline
 * styles directly on the target elements based on window width, and re-applies
 * on resize and on DOM mutation (since this is a React app — re-renders from
 * clicking pills/tabs/menus can reset inline styles on the nodes it re-renders).
 */
(function () {
  var SIDEBAR_BREAKPOINT = 900;
  var DAY_COLUMN_BREAKPOINT = 720;
  var PINS_ROW_BREAKPOINT = 640;

  // Bug fix, not width-gated: the profile header row (avatar + name/status +
  // "View latest screenshot" button) already declares flex-wrap: wrap, but its
  // middle child resets min-width to 0, which lets the browser shrink that child
  // to near-nothing instead of ever wrapping — the name text then overflows under
  // the button rather than dropping to its own line.
  function fixProfileRow() {
    var rows = document.querySelectorAll(
      'div[style="display: flex; align-items: center; gap: 12px; flex-wrap: wrap;"]'
    );
    rows.forEach(function (row) {
      var nameCol = row.children[1];
      if (nameCol && nameCol.tagName === "DIV") {
        nameCol.style.setProperty("min-width", "160px", "important");
      }
    });
  }

  // Tabs row (MEMBERS / ALL / ME) — allow wrapping instead of overflowing the page.
  function fixTabsRow() {
    var rows = document.querySelectorAll('div[style*="align-items: flex-end"]');
    rows.forEach(function (row) {
      row.style.setProperty("flex-wrap", "wrap", "important");
      row.style.setProperty("row-gap", "8px", "important");
    });
  }

  // Remembers each element's ORIGINAL inline width/flex (captured the first time
  // we touch it) so restoring the "wide" state puts back the app's real value
  // instead of an empty property that the app itself won't necessarily refill.
  var originalWidth = new WeakMap();
  var originalFlex = new WeakMap();

  // Sidebar — auto-collapse to an icon-only rail below tablet width so the fixed
  // 240px column stops forcing the whole page into horizontal scroll.
  function fixSidebar(narrow) {
    var aside = document.querySelector("aside");
    if (!aside) return;

    if (!originalWidth.has(aside)) {
      originalWidth.set(aside, aside.style.width || "240px");
    }

    if (narrow) {
      aside.style.setProperty("width", "64px", "important");
    } else {
      aside.style.setProperty("width", originalWidth.get(aside), "important");
    }

    aside.querySelectorAll('span[style="flex: 1 1 0%;"]').forEach(function (label) {
      label.style.display = narrow ? "none" : "";
    });

    var headerRow = aside.firstElementChild;
    if (headerRow) {
      var imgs = headerRow.querySelectorAll("img");
      if (imgs[1]) imgs[1].style.display = narrow ? "none" : "";
    }
  }

  // Pinned-members row — the spec has this wrap to multiple lines at every
  // width, but on a real phone that means 5 rows of pills (~250-300px) before
  // any dashboard content is visible, and it forces 2D scanning instead of 1D.
  // Below mobile width, switch it to a single horizontally-scrollable row
  // instead (matching the Time & activity row's existing scroll pattern).
  function fixPinsRow(narrow) {
    // Located via the "+" add button's parent rather than by matching the row's
    // own style string — this function mutates that exact string (flex-wrap),
    // so a selector built from the pre-mutation value stops matching after the
    // first toggle.
    var addIcon = Array.from(document.querySelectorAll("span")).find(function (s) {
      return (
        s.textContent.trim() === "add" &&
        s.className &&
        s.className.indexOf("material-symbols") !== -1
      );
    });
    var addButton = addIcon ? addIcon.closest("button") : null;
    // The button sits inside its own small positioning wrapper (for the
    // limit-reached tooltip) before the real pills row — walk up until we
    // find the ancestor that actually holds the pill collection.
    // Don't key on flex-wrap — this row's inline style is regenerated by the
    // app itself at the 10-pin limit and that render happens to drop the
    // flex-wrap declaration entirely (App-side inconsistency between its own
    // render branches, not something we control). "align-items: center" +
    // "gap: 8px" are present in both observed variants.
    var row = null;
    var cur = addButton ? addButton.parentElement : null;
    for (var i = 0; i < 4 && cur; i++) {
      var s = cur.getAttribute("style") || "";
      if (
        s.indexOf("align-items: center") !== -1 &&
        s.indexOf("gap: 8px") !== -1 &&
        cur.children.length >= 3
      ) {
        row = cur;
        break;
      }
      cur = cur.parentElement;
    }
    if (!row) return;

    if (narrow) {
      row.style.setProperty("flex-wrap", "nowrap", "important");
      row.style.setProperty("overflow-x", "auto", "important");
      row.style.setProperty("padding-bottom", "4px", "important");
    } else {
      row.style.setProperty("flex-wrap", "wrap", "important");
      row.style.removeProperty("overflow-x");
      row.style.removeProperty("padding-bottom");
    }

    Array.from(row.children).forEach(function (pill) {
      if (narrow) {
        pill.style.setProperty("flex-shrink", "0", "important");
      } else {
        pill.style.removeProperty("flex-shrink");
      }
    });
  }

  // Time & activity day columns — per spec, below 720px columns should stop
  // shrinking at 88px and let the row's existing overflow-x: auto scroll instead
  // of squeezing 7 columns unreadably thin.
  function fixDayColumns(narrow) {
    document.querySelectorAll(".hs-days > div").forEach(function (col) {
      if (!originalFlex.has(col)) {
        originalFlex.set(col, col.style.flex || "1 1 0%");
      }
      if (narrow) {
        col.style.setProperty("flex", "0 0 88px", "important");
        col.style.setProperty("min-width", "88px", "important");
      } else {
        col.style.setProperty("flex", originalFlex.get(col), "important");
        col.style.removeProperty("min-width");
      }
    });
  }

  // apply() itself writes style attributes, and the observer below watches
  // style attributes (see why below) — without disconnecting first, every
  // apply() would immediately re-trigger itself in an infinite loop.
  function apply() {
    observer.disconnect();
    var w = window.innerWidth;
    fixProfileRow();
    fixTabsRow();
    fixSidebar(w <= SIDEBAR_BREAKPOINT);
    fixDayColumns(w <= DAY_COLUMN_BREAKPOINT);
    fixPinsRow(w <= PINS_ROW_BREAKPOINT);
    observer.observe(document.documentElement, {
      childList: true,
      subtree: true,
      attributes: true,
      attributeFilter: ["style"],
    });
  }

  var scheduled = false;
  function schedule() {
    if (scheduled) return;
    scheduled = true;
    requestAnimationFrame(function () {
      scheduled = false;
      apply();
    });
  }

  window.addEventListener("resize", schedule);
  // Watch style-attribute rewrites too, not just added/removed nodes — this
  // framework sometimes regenerates an element's whole style attribute on
  // re-render (e.g. the pins row when the 10-pin limit is hit) with no
  // structural change, which a childList-only observer would miss entirely.
  var observer = new MutationObserver(schedule);
  observer.observe(document.documentElement, {
    childList: true,
    subtree: true,
    attributes: true,
    attributeFilter: ["style"],
  });

  // Belt-and-suspenders: some of this app's own re-renders land AFTER the
  // mutation that triggered them (async state updates, transition end, etc.),
  // occasionally racing past a single observer callback. A cheap poll makes
  // the fix eventually-consistent regardless of exactly when that lands.
  setInterval(apply, 500);

  apply();
})();
